### ISSUE TITLE
Some anime not opening.

### ISSUE THREAD

**Issue by GoluLiliput** [kl3jvi/animity#103]
There are some anime which aren't showing any episode. They are just showing the name and limited data including the synopsis of the anime but the actual episodes doesn't show up. I have got quite a few in my usage but i ignored it thinking it as a fluke but i face it quite a few times now. Though I don't remember each anime that didn't show up, i remember 'Black Clover' as an example. It doesn't get h the episode list of that anime.

Please fix this bhai!

**Comment by GoluLiliput** [comment]
But they do exist on gogoanime. Both 'Black Clover'(1 episode) and 'Black Clover (TV)'(170 episodes). The app doesn't show the TV version in it's database even though it's scraping gogoanime. And the normal 'Black Clover' shows no episodes. This happens with some other anime too. I am attaching screenshot for your reference.

**Comment by GoluLiliput** [comment]
![Screenshot_20220617-002425_Chrome.jpg](https://user-images.githubusercontent.com/60719832/174146039-0ae8ba43-85ff-4195-b465-233fd43882a5.jpg)![Screenshot_20220617-002401_Chrome.jpg](https://user-images.githubusercontent.com/60719832/174146051-ae1ce725-2334-4f76-8c15-f2ff6ecff542.jpg)![Screenshot_20220617-002252_Chrome.jpg](https://user-images.githubusercontent.com/60719832/174146069-fecf7fc3-6a55-4725-9a35-a832299a71ed.jpg)

**Comment by GoluLiliput** [comment]
![Screenshot_20220617-004018_Animity.jpg](https://user-images.githubusercontent.com/60719832/174147076-5606fb48-5360-453a-ab2d-32cb6f9ea526.jpg)

**Comment by ChaosGodEmperor** [comment]
You're wrong. It does show up on the app.
![Screenshot_20220616-180430_Animity](https://user-images.githubusercontent.com/98984322/174202117-de65f6e0-41d2-43e7-8bed-907f8fac8bdc.jpg)
![Screenshot_20220616-180421_Animity](https://user-images.githubusercontent.com/98984322/174202121-1c9a0059-3f2b-4993-a958-9c4ab2a16c68.jpg)

**Comment by Myst400** [comment]
> There are some anime which aren't showing any episode. They are just showing the name and limited data including the synopsis of the anime but the actual episodes doesn't show up. I have got quite a few in my usage but i ignored it thinking it as a fluke but i face it quite a few times now. Though I don't remember each anime that didn't show up, i remember 'Black Clover' as an example. It doesn't get h the episode list of that anime.
> 
> Please fix this bhai!

Update the app. Think it's something related to the 1.1.0 app cause I had that issue w dawn of the witch and the current precure not showing episodes. They showed up after I updated to 1.1.1

**Comment by Myst400** [comment]
> You're wrong. It does show up on the app. ![Screenshot_20220616-180430_Animity](https://user-images.githubusercontent.com/98984322/174202117-de65f6e0-41d2-43e7-8bed-907f8fac8bdc.jpg) ![Screenshot_20220616-180421_Animity](https://user-images.githubusercontent.com/98984322/174202121-1c9a0059-3f2b-4993-a958-9c4ab2a16c68.jpg)

You're probably using a different version of the app from the op since I also ran into op's issue and turned out I just needed to update to new app version

**Comment by GoluLiliput** [comment]
No . It didn't fix for me even after update. Just go on to ur anilist account in the app and try to open animes from there. U will see most of them won't show any episodes.. my problem is still persisting.

**Comment by GoluLiliput** [comment]
![IMG_20220617_130442.jpg](https://user-images.githubusercontent.com/60719832/174249453-411ea490-5ebd-4e3b-b33e-58ed5925e4e2.jpg)![IMG_20220617_130427.jpg](https://user-images.githubusercontent.com/60719832/174249440-023259bc-0748-49fc-ba24-c62082d58cdf.jpg)
All these animes , for example, aren't opening up for me. There are much more. I guess the problem here is that the app is showing catalogue according to Anilist and fails to sometimes link episodes to the spicif anime title from Gogoanime. That's y u can't find 'Black Clover TV' and 'Black Clover' separately in the app cuz it's no present in anilist but is present in Gogo.

**Comment by Myst400** [comment]
> ![IMG_20220617_130442.jpg](https://user-images.githubusercontent.com/60719832/174249453-411ea490-5ebd-4e3b-b33e-58ed5925e4e2.jpg)![IMG_20220617_130427.jpg](https://user-images.githubusercontent.com/60719832/174249440-023259bc-0748-49fc-ba24-c62082d58cdf.jpg) All these animes , for example, aren't opening up for me. There are much more. I guess the problem here is that the app is showing catalogue according to Anilist and fails to sometimes link episodes to the spicif anime title from Gogoanime. That's y u can't find 'Black Clover TV' and 'Black Clover' separately in the app cuz it's no present in anilist but is present in Gogo.

Weird def is a you thing. Do you have any VPN like programs up? I can get all of those in the app w episodes

**Comment by GoluLiliput** [comment]
Yeah I tried applying normal search to the anime titles too. They don't open up the episode list. See these things don't show up no matter how much i wait. I ain't using VPN of any sorts too.![IMG_20220617_174406.jpg](https://user-images.githubusercontent.com/60719832/174296140-569bbebc-ac6d-44cc-aa7c-134152927b98.jpg)
These titles doesn't show up complete details and doesn't fetch episodes.
