### ISSUE TITLE
App improvements & suggestions 

### ISSUE THREAD

**Issue by cutterchop** [kl3jvi/animity#11]
I acknowledged that this app is being rebuilt and under development but im giving a early list of stuff to do for a better approach for your app 
First App overall in current state

- Overall the app does its job but it feels really limited to use and is not a app that catches interest , first of all going through the sections explore and favorites the animation art added aren't useful what so ever its probably consuming and wont add much effect i would suggest removing it , second i would recommend adding mal sync , this shouldn't be slept on or further delayed because it limits the app way more , lets assume you added mal sync now then with it you should change the apps whole ui into a mal client style, this means when someone logins their account they have a whole page that shows what is planned, watching , dropped etc all in sections within 1 page, then the current home page in your app can be named explore and people can search from with in there, here is a example of how it should be 
![1](https://user-images.githubusercontent.com/31880937/139425897-c36f43f8-3c99-42e5-a20a-c6f5cbe7d1f7.png)
 the reason why it should be like this is because apps like this catches most interest ( and were the ones that got most popular ) and is extremely useful, now to continue on the reason why the app feels limited with all the stuff i listed above their is also a reason which is the app sets you up in boundaries without any settings just a box , so people with experience with previous app will quickly drop it off , you will add settings most probably but just a heads up, what settings should include ?  a small theme customizer , in app updater , show filler episodes , hide dubbed anime it can go on for longer but to make it easier for both of us i got something you can benefit from greatly [check this app out it written with kotlin and offers the same job you can take a look around it and its open source so you can look at the code and maybe use some of it](https://github.com/deceptions/no) and one more app [here](https://github.com/LagradOst/CloudStream-3) now to continue with the app i want to note something about its name and logo , both can have improvements , the name is always urs to choose but lets state some thing apps with anim on the start is generic now , the logo is fine you could make the A in the logo a little bigger and more straight , but its just my opinion on this, if you have the commitment and want to make the app good please heed this issue, i joined your discord and ill add more to this in time , and maybe its to much but im no developer this app is being rebuilt so its time to receive all of this , to continue on the matter Sources , i believe the app should have the main sources for now that should be Gogoanime and zoro you can try and code torrents into streaming but im no expert , i seen that downloading was suggested, lots of apps have downloading feature but once someone downloads more then 2 at once it all goes to shit so be ware of that , have a bulk delete and download option let people que downloads, you can also add support to external download managers for some.

- finally Bugs , i read your discord chat and you got some input on that by other users so i wont provide much here but i did notice when you go inside a show there are these weird lines , im guessing its a bug 

![2](https://user-images.githubusercontent.com/31880937/139428971-64f606d5-8d28-45b0-a69f-679014642015.png)
 
and that's it take care man and hopefully you become a good dev one that listens to the community 

good luck..

**Comment by kl3jvi** [comment]
I will try to do my best with these suggestions :). I am closing this and will get back to this for anything.
