### ISSUE TITLE
Videos still not playing

### ISSUE THREAD

**Issue by Dvixe** [kl3jvi/animity#114]

**Comment by kl3jvi** [comment]
Hi this issue has been fixed.

**Comment by Drangonfly30** [comment]
Sorry, but I still can't play any video.

**Comment by kl3jvi** [comment]
> Sorry, but I still can't play any video.

Please download latest [release](https://github.com/kl3jvi/animity/releases/tag/v0.1.7) app and try.

**Comment by Drangonfly30** [comment]
Yeah I have already tried latest build but still having same issue.
