### ISSUE TITLE
Present the next episode in long animes

### ISSUE THREAD

**Issue by ITADORI-15** [kl3jvi/animity#115]
So I was watchin one piece
I reached abt 70 episodes and found tat whenever I had to watch the next episode I have to scroll all the way to 71 episode....again and again
Its painfull 😭
Hope u can do something about it
Thanks❤

**Comment by kl3jvi** [comment]
I just updated the app, now they are chunked by 50 episodes, will be part of the next release :)

**Comment by ITADORI-15** [comment]
> So I was watchin one piece
> I reached abt 70 episodes and found tat whenever I had to watch the next episode I have to scroll all the way to 71 episode....again and again
> Its painfull 😭
> Hope u can do something about it
> Thanks❤

Think abt the ppl who r watching one piece😁
