### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BLVCK-ANGEL** [kl3jvi/animity#117]
Some anime Episodes Not appearing

1. Go to App
3. Click on Any Anime
4. Scroll down to Episode list
5. See error

Screenshots is [Attached]([url](![WhatsApp Image 2022-12-31 at 10 34 06 AM](https://user-images.githubusercontent.com/83200567/210125780-6eab2729-54f9-4674-bb9b-733e46fcb81f.jpeg)))

**Smartphone (please complete the following information):**
 - Device: [Poco F1]
 - OS: [ Android 10]

**Comment by ITADORI-15** [comment]
> 
> Some anime Episodes Not appearing
> 
> Steps to reproduce the behavior:
> 1. Go to App
> 3. Click on Any Anime
> 4. Scroll down to Episode list
> 5. See error
> 
> 
> Screenshots is [Attached]([url](![WhatsApp Image 2022-12-31 at 10 34 06 AM](https://user-images.githubusercontent.com/83200567/210125780-6eab2729-54f9-4674-bb9b-733e46fcb81f.jpeg)))
> 
> **Smartphone (please complete the following information):**
>  - Device: [Poco F1]
>  - OS: [ Android 10]
> 
> 
> 

Same prob

**Comment by LynBean** [comment]
Same problem with same phone model
