### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GoluLiliput** [kl3jvi/animity#122]
The app crashes when any anime page is opened.

1. Open any anime from the app
2. Wait for sometime, the app crashes automatically

Expected behavior- The shouldn't crash

 - Device: Xiaomi K20 Pro
 - OS: Android 12
 - Version 1.1.3

**Comment by kl3jvi** [comment]
please reinstall app

**Comment by GoluLiliput** [comment]
> please reinstall app
> 

I reinstalled by redownloading apk. It still crashes. 
1. It takes time to load up the homepage of the app 
2. When i click on few anime, the app crashes. Eg- Your name

**Comment by kl3jvi** [comment]
Can't reproduce your error,let’s see if it happens to others and I will fix it as soon as possible

**Comment by Jwjshhi** [comment]
Same happened to me 
The app wasn't working after i installed it first.
After i reinstalled it . It's taking too much time to load
Even when i search an anime it takes a lot of time to load
Device:realme 6i

**Comment by kl3jvi** [comment]
Fixed
