### ISSUE TITLE
Episode list loading taking more time

### ISSUE THREAD

**Issue by itsmeshibintmz** [kl3jvi/animity#123]
**Describe the bug**
The episode list is taking so much time to load , I thought the app is useless(newcomer)

**To Reproduce**
1. Go to 'App'
2. Click on 'any show'
3. Check for episodes
4. See error that episodes are not showing for a long time and some are not loading

**Expected behavior**
Episodes are expected to load when we click the anime details.

**Screenshots**
![Screenshot_20230402-074248.png](https://user-images.githubusercontent.com/52344717/229327372-3adcbc5d-0d36-4acd-b2d5-76217e32a333.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Nothing Phone(1)]
 - OS: [Android 13]
 - Version [1.1.3]

**Additional context**
Please fix asap.

**Comment by kl3jvi** [comment]
fixed

**Comment by professorDeveloper** [comment]
Hello, can we work with you?

**Comment by kl3jvi** [comment]
Hey @professorDeveloper sure, this app is open source :)

**Comment by professorDeveloper** [comment]
thanks bro  i have an application project can you do it if the price is negotiable
