### ISSUE TITLE
Update Description

### ISSUE THREAD

**Issue by EdwinRodger** [kl3jvi/animity#126]
In first line of description it's written -

> The app doesn't require account creation to use it.

The [first screenshot](https://github.com/kl3jvi/animity/blob/main/assets/asset1.png) has _Continue As Guest_ option

But when I downloaded the app, I didn't saw Continue As Guest option

<details>

<summary>Screenshot</summary>

![animity](https://user-images.githubusercontent.com/92982808/234896620-562f0d1c-7163-4355-99f8-d58bae71c39b.jpg)

</details>

I just wanted to try the app but couldn't because of AniList login. Just a friendly reminder to update the description.

**Comment by kl3jvi** [comment]
This is your chance to make a contribution :)
