### ISSUE TITLE
App crashing with error

### ISSUE THREAD

**Issue by ChaosGodEmperor** [kl3jvi/animity#138]
![Screenshot_20230913_092915_Animity](https://github.com/kl3jvi/animity/assets/98984322/b5eaf0c0-ec77-4aed-a8b2-1dc8d84cd4ff)
**Describe the bug**
App didn't load and crashed on startup with error message "Http request failed with status code `400`"

**To Reproduce**
1. Go to app
2. See error
3. App crashes after a few seconds

**Expected behavior**
App didn't load and start normally

**Screenshots**
See attached file on top

**Desktop (please complete the following information):**
 - Version 1.2.0 (newest version)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold4
 - OS: Android 13
 - One UI 5.1.1

**Additional context**
Uninstalling app, downloading it again and reinstalling it didn't fix the issue.

**Comment by ChaosGodEmperor** [comment]
Fixed it by clearing cache and data.

**Comment by professorDeveloper** [comment]
> Fixed it by clearing cache and data.

bro your vpn on 
?

**Comment by professorDeveloper** [comment]
> Fixed it by clearing cache and data.

Bro your phone vpn is turn on  ?
