### ISSUE TITLE
Question: Why are you hiding code bro, aren't you open to PR's?

### ISSUE THREAD

**Issue by IndusAryan** [kl3jvi/animity#144]
also this is not good FOSS practice

**Comment by kl3jvi** [comment]
Hi yes I am aware of the foss practices. A lot of anime apps get hit by DMCA so i hid the code. If you want to create pr I can give you access

**Comment by IndusAryan** [comment]
ok, i dont need as of now, but gogo parser is fine, it will work when domain will be changed to 

https://anitaku.to

they rebranded themselves
and they are testing cloudlare frequently
