### ISSUE TITLE
[Bug] App crashes when choosing an anime to watch.

### ISSUE THREAD

**Issue by obakha** [kl3jvi/animity#157]
**Describe the bug**
The app crashes upon clicking an anime.

**To Reproduce**
1. Open app
2. Succesfully login to Anilist.
3. In settings, I chose gogoanime as provider.
4. Click on any anime shown.
4. App crashes, with no error mesage shown.

**Expected behavior**
Upon clicking an anime, show anime details and episodes list, then when clicking an episode, the app plays the episode on its built-in player.

**Smartphone (please complete the following information):**
 - Device: [Samsung A04]
 - OS: [Android 10]
 - Version [1.2.7]

**Comment by kl3jvi** [comment]
Hi what is the issue?

**Comment by obakha** [comment]
After, I install the app (universal and armeabi-v7a).
I login with my Anilist account, after that the app shows its catalogue of animes, I then tried to tap on any anime just to test it out, the app then crashes and just kick me out of it.

**Comment by obakha** [comment]
The crashing problem stopped when I enabled Google Play Services. But now it seems like the sources are broken, most of the animes I tried to watch don't seem to work. (Case closed, HXH, Jujutsu Kaisen) using both Gogo and Kaido didn't work.
