### ISSUE TITLE
App freeze with anime with a lot of episodes + search issue

### ISSUE THREAD

**Issue by Faresgmr** [kl3jvi/animity#16]
If I open one piece episode page the app freezes for a bit (tested on SM-T585)
Also If I try to search for other anime while results from previous search are there it shows results from both searches and sometimes doesn't let me search
![Screenshot_20211114-010444_Animity](https://user-images.githubusercontent.com/63611149/141661546-3c00cfb6-b9f1-459d-9c30-57d77184dd26.jpg)

**Comment by kl3jvi** [comment]
I think I know the issue. Thanks for reporting mate. I will upload a new update soon

**Comment by kl3jvi** [comment]
I fixed the search bug, and uploaded a new build, as for the animes with a lot of episodes I couldn't reproduce. Thanks for reportin.
