### ISSUE TITLE
Having a problem when installing the app

### ISSUE THREAD

**Issue by 13thamayun** [kl3jvi/animity#19]
![Screenshot_20211203-140201_SAI](https://user-images.githubusercontent.com/90797582/144615167-43756767-e85d-41fb-b110-2ea1952dee6f.jpg)

This pops up when i try to install the application, is this happening to anyone else?

**Comment by kl3jvi** [comment]
Hi there! Please uninstall the old app and reinstall because I changed signing certificate of the app. Thank you :)

**Comment by 13thamayun** [comment]
Great its been fixed thanks
