### ISSUE TITLE
E ke problem ta perdor ate serverin nga ku ben stream?

### ISSUE THREAD

**Issue by fabriciopashaj** [kl3jvi/animity#2]
Kam bere nje downloader qe shkarkonte anime nga 4anime.to dhe ajo u mbyll dhe keto faqet e tjera perdorin chapta apo gjera si ajo, prandaj nuk u bej do scrape link-eve qe kane ato.

**Comment by kl3jvi** [comment]
Nqs do te te jap te drejte te shohesh scraperin tim me shkruaj emailin

**Comment by fabriciopashaj** [comment]
Se mos na e hakeron
fabriciopashaj.dev@gmail.com

**Comment by fabriciopashaj** [comment]
Edhe e pash kte streamerin qe ke ber, me duket se I ben stream nga nje url herokuapp apo ku ta di un, edhe un per ate pyeta

**Comment by fabriciopashaj** [comment]
Flm!

**Comment by fabriciopashaj** [comment]
O vlla, po ky cfar ka qe nuk pergjigjet
![Screenshot_20210831-161620](https://user-images.githubusercontent.com/79104733/131509789-50a1041b-99ca-4a57-b568-6694ea7cba22.png)

**Comment by fabriciopashaj** [comment]
Serveri

**Comment by kl3jvi** [comment]
Ka ndryshuar URL gogoanime hostoje ne glitch ose tek heroku scraperin tim dhe perdore

**Comment by fabriciopashaj** [comment]
po url-ja qe perdor scraperi punon

**Comment by kl3jvi** [comment]
po punon

**Comment by fabriciopashaj** [comment]
po ca problemi ka pastaj?

**Comment by fabriciopashaj** [comment]
se s'dua dhe te te bezdis

**Comment by kl3jvi** [comment]
https://rhinestone-bow-ketchup.glitch.me/api/v1

**Comment by kl3jvi** [comment]
> se s'dua dhe te te bezdis

Pa problem

**Comment by fabriciopashaj** [comment]
po deshe mund te flasim edhe ne discord se kjo me github issues esht pak bezdi `fabricio#0365`
