### ISSUE TITLE
CLEARTEXT error

### ISSUE THREAD

**Issue by Skrixie** [kl3jvi/animity#27]
Im having an issue where it displays a CLEARTEXT error 
![Screenshot_2021-12-23-16-17-17-036_com kl3jvi animity](https://user-images.githubusercontent.com/76206752/147210464-c8c99449-3f4b-4502-948d-d800e7f9043d.jpg)

**Comment by kl3jvi** [comment]
Please uninstall app and reinstall latest version, I just updated the apps. Thanks for reporting 👍🏻
