### ISSUE TITLE
Videos won't play 

### ISSUE THREAD

**Issue by LyricXP** [kl3jvi/animity#28]
Like the title says,whenever I go to play a video, I just sit on  a black screen.

**Comment by kl3jvi** [comment]
Hi, thanks I am investigating this issue 👍🏻

**Comment by LyricXP** [comment]
![Screenshot_20211227-211624_Animity.jpg](https://user-images.githubusercontent.com/96715850/147527466-4d10653b-6f41-490c-8d63-454bee193a31.jpg)

Sits on this screen. Even if I skip the intro, sit&wait, try to go to the previous or next episode and if u switch shows.

**Comment by Myst400** [comment]
Having the same issue I wonder if it's related to gogo error alert I would get on the version before this

**Comment by bluehashtagger** [comment]
Hope you guys it soon

**Comment by kl3jvi** [comment]
I will be working on this today as I am free.

**Comment by bluehashtagger** [comment]
Yay

**Comment by HelpMeGetANamePlease** [comment]
The same thing is happening on Animexstream too.

**Comment by Myst400** [comment]
> The same thing is happening on Animexstream too.

I'm guessing it has something to do w gogo animu since that's what I saw a error notice about before I updated when I tried to watch

**Comment by LyricXP** [comment]
> I will be working on this today as I am free.

Any time updates?

**Comment by Myst400** [comment]
Still down though the api code has been updated

**Comment by bluehashtagger** [comment]
did the dev die of api update?

**Comment by ITADORI-15** [comment]
@kl3jvi 
Please get it ready asap......we all are waiting for ur reply

**Comment by LyricXP** [comment]
> @kl3jvi 
> Please get it ready asap......we all are waiting for ur reply

There's this website/app called Zoro.to and it works like a charm. Definitely recommend it.

**Comment by LyricXP** [comment]
https://zoro.to/home?source=pwa#.YeRcK9oDYMU.link

Try this out everyone

**Comment by kl3jvi** [comment]
It's a major problem that happens in the gogo site. They have encrypted the streaming url. I think I have found a workaround but no promises I need some time to test it out. If this doesnt work I will have to build a new scraper.

**Comment by kl3jvi** [comment]
I finally fixed it! Please download latest version!

**Comment by bluehashtagger** [comment]
Huzzah!!!!!!
