### ISSUE TITLE
Videos wont play

### ISSUE THREAD

**Issue by ITADORI-15** [kl3jvi/animity#36]
I hve downloaded the latest version .....but still it says Couldnt find a stream for this anime

**Comment by HelpMeGetANamePlease** [comment]
But the episode plays after that message.

**Comment by ITADORI-15** [comment]
Oh is it lemme check

**Comment by ITADORI-15** [comment]
Nope it gets stuck here![Screenshot_20220117-112037_Animity.jpg](https://user-images.githubusercontent.com/83289685/149714843-143564f6-7e80-4ecf-b4c5-568dc8eb97a9.jpg)

**Comment by HelpMeGetANamePlease** [comment]
It's working on my device but I can't change the video quality.

**Comment by ITADORI-15** [comment]
Ohh ok

**Comment by kl3jvi** [comment]
> It's working on my device but I can't change the video quality.

As I mentioned the last update fetches the best quality possible for an episode, because the stream is not progressive in most cases but is mp4 so it has static stream quality!

**Comment by RYUkenji123** [comment]
This app is so good but it shows couldn't find a stream then starts playing

**Comment by kl3jvi** [comment]
> This app is so good but it shows couldn't find a stream then starts playing

Is this an issue after all days without streaming?

**Comment by ITADORI-15** [comment]
We didn't understand what u meant @kl3jvi

**Comment by kl3jvi** [comment]
I mean this small issue isnt causing any trouble, its a small tweak I will fix it later.

**Comment by ITADORI-15** [comment]
Yeah...thanks btw
