### ISSUE TITLE
Videos resolution cannot be changed in the latest version. 

### ISSUE THREAD

**Issue by HelpMeGetANamePlease** [kl3jvi/animity#37]
The episode play now but I can't change the video quality.
There's only
(Auto)
1080p

**Comment by ITADORI-15** [comment]
Which anime are u watching

**Comment by ITADORI-15** [comment]
Coz none of them are loading for me

**Comment by HelpMeGetANamePlease** [comment]
> Which anime are u watching

One Piece
Heavenly Sword
Platinum End

**Comment by kl3jvi** [comment]
The stream now is not m3u8 progressive anymore, it's only mp4 which has static streaming quality. For this build I am using the best quality possible per episode. I will try to create a dialog for choosing streaming quality on episode click.

**Comment by ITADORI-15** [comment]
Best quality available per episode huh?......Ig this is the best update ever....thanks **Bigg manh!**
