### ISSUE TITLE
SOME ANIME WONT PLAY

### ISSUE THREAD

**Issue by Carnaken** [kl3jvi/animity#38]
![Screenshot_20220118_095118](https://user-images.githubusercontent.com/81844464/149852375-f023867c-b901-4e51-853b-379c13ad1409.jpg)
T
![Screenshot_20220118_095045](https://user-images.githubusercontent.com/81844464/149852380-e0b2afc3-c8ea-4e1e-a583-f54057a0c8d4.jpg)
This 
![Screenshot_20220118_094740](https://user-images.githubusercontent.com/81844464/149852383-aad0e96d-0725-475c-a971-ebc4a52b6c7b.jpg)

This photo are proof that some video wont play.

**Comment by ITADORI-15** [comment]
Bro try deleting cache and app data
Coz when this happened 2 me I tried doing tat and it worked...idk why tho

**Comment by Carnaken** [comment]
> Bro try deleting cache and app data Coz when this happened 2 me I tried doing tat and it worked...idk why tho

I already try this but still its not working.

**Comment by kl3jvi** [comment]
![Screenshot_2022-01-18-08-05-37-708_com kl3jvi animity](https://user-images.githubusercontent.com/40796367/149887585-57ba11c7-d25d-441e-9f9b-f1e18d3b3db0.jpg)
Please reinstall app cuz its working 😄
