### ISSUE TITLE
Bro app related query

### ISSUE THREAD

**Issue by ITADORI-15** [kl3jvi/animity#40]
Is it just for me or every1 else
It's like as if the app takes breaks
It plays the videos whenever it wants
It isnt working always
I mean 2 say is when I tried playing a video at 7 30 PM nothing but a black screen came
But just now at 8 48 PM when I started playing it worked perfectly fine.
Plz fix the issue
Dont know if it's for every1 or just me

**Comment by ITADORI-15** [comment]
![Screenshot_20220120-091724_Animity.jpg](https://user-images.githubusercontent.com/83289685/150269826-5b2bc2c0-b684-4234-8814-fd73605dd4fe.jpg)
U can see that the app isnt working currently bro.

**Comment by kl3jvi** [comment]
Are you on wifi or data?

**Comment by ITADORI-15** [comment]
Wifi

**Comment by GABIlopez** [comment]
![Screenshot_20220121-001452_Animity.jpg](https://user-images.githubusercontent.com/32043783/150459462-b4493ea7-768b-4946-8d37-f11635af79de.jpg)

**Comment by ITADORI-15** [comment]
Hey so there is 1 atleast who has the same problem as me🤣@GABIlopez
