### ISSUE TITLE
MAJOR UPDATE !!!

### ISSUE THREAD

**Issue by kl3jvi** [kl3jvi/animity#43]
I am working on integrating ANILIST in Animity!!!!

**Comment by ITADORI-15** [comment]
I swear this will be one of the best updates for your app
🥳🥳🥳🥳🥳🤯🤯🤯🤯

**Comment by JasonBlitz5** [comment]
Great news! Will you do the same for MAL is the future?

**Comment by kl3jvi** [comment]
**Question:** I am not that much into anime tracking sites, but I'm lookin up some site called kitsu. Is this one better than anilist or should I keep adding anilist?

**Comment by JasonBlitz5** [comment]
> **Question:** I am not that much into anime tracking sites, but I'm lookin up some site called kitsu. Is this one better than anilist or should I keep adding anilist?

Anilist. Also try to add MyAnimeList (MAL) if you can

**Comment by kl3jvi** [comment]
> > **Question:** I am not that much into anime tracking sites, but I'm lookin up some site called kitsu. Is this one better than anilist or should I keep adding anilist?
> 
> Anilist. Also try to add MyAnimeList (MAL) if you can

Any reason this one is better than kitsu as I'm checkin their api is easier to integrate?

**Comment by ITADORI-15** [comment]
Ig the best is anilist....plz add anilist

**Comment by JasonBlitz5** [comment]
> > > **Question:** I am not that much into anime tracking sites, but I'm lookin up some site called kitsu. Is this one better than anilist or should I keep adding anilist?
> > 
> > 
> > Anilist. Also try to add MyAnimeList (MAL) if you can
> 
> Any reason this one is better than kitsu as I'm checkin their api is easier to integrate?

More people use Anilist than kitsu so it would be a better addition cause more people will use It. Rather add something that more people would use then something not many people use

**Comment by kl3jvi** [comment]
I see, okay thanks a lot for your opinion.

**Comment by kl3jvi** [comment]
Also:
What should I sync with this site?
episodes only right?

**Comment by ITADORI-15** [comment]
Yeah that will be fine if
Also if recommendations are shown it will be good
I suggest u to take a look at the anilist.co website 
Then u can choose what 2 add and what not 2

**Comment by kl3jvi** [comment]
**What do you think about this login page?**
![Screenshot_1643551615](https://user-images.githubusercontent.com/40796367/151703097-e911ae02-1a72-4bc1-999b-384825b6040a.png)
e

**Comment by JasonBlitz5** [comment]
> **What do you think about this login page?** ![Screenshot_1643551615](https://user-images.githubusercontent.com/40796367/151703097-e911ae02-1a72-4bc1-999b-384825b6040a.png) e

Looks great!

**Comment by ITADORI-15** [comment]
That's pretty good

**Comment by ITADORI-15** [comment]
Nowadays most ppl use anilist rather than MAL
No offense but is it really that good(MAL)?

**Comment by kl3jvi** [comment]
> > **What do you think about this login page?** 
> 
> Looks great! Also if I may ask again(sorry about that) can you try to add MAL (My Anime List) as well?

Thanks!!  That will be for a future update bro, as I'm working on adding anilist first. And I saw they have a pretty bad api and old one.

**Comment by JasonBlitz5** [comment]
> Nowadays most ppl use anilist rather than MAL No offense but is it really that good(MAL)?

Imo yes. Plus it gives the people who don't use Anilist at all/as much another place to login without making a whole new account and stuff

**Comment by JasonBlitz5** [comment]
> 

Ok Good to know!

**Comment by JasonBlitz5** [comment]
> > > **What do you think about this login page?**
> > 
> > 
> > Looks great! Also if I may ask again(sorry about that) can you try to add MAL (My Anime List) as well?
> 
> Thanks!! That will be for a future update bro, as I'm working on adding anilist first. And I saw they have a pretty bad api and old one.

Ok good to know!

**Comment by kl3jvi** [comment]
Thanks a lot for your opinions ^^

**Comment by JasonBlitz5** [comment]
> Thanks a lot for your opinions ^^

No problem!

**Comment by ITADORI-15** [comment]
Hey Jason thanks manh....I also wanted 2 know
Bro @kl3jvi by when will it be completed?

**Comment by kl3jvi** [comment]
> Hey Jason thanks manh....I also wanted 2 know Bro @kl3jvi by when will it be completed?

I have completed Login part but finding a bit hard how to sync api with gogo tho. If I find an easy way to do this It may be finished by the end of week. No promises tho

**Comment by ITADORI-15** [comment]
I thought it would take around a month but hearing the word week made me happy tho
Thnx bro

**Comment by kl3jvi** [comment]
@ITADORI-15 It's a big update so please bear with me!

**Comment by ITADORI-15** [comment]
Hey bro it's no problem
Ur the person working hard...
Hope it will be done soon
Best of luck
THANKS

**Comment by kl3jvi** [comment]
**Another Question:**  I am adding sync with anilist, I think the local database for saving favorite animes is not needed anymore right ? @ITADORI-15 @JasonBlitz5 What do you think ?

**Comment by ITADORI-15** [comment]
Yeah correct
Since ur adding anilist there's no need for the favourite section anymore

**Comment by JasonBlitz5** [comment]
> **Another Question:** I am adding sync with anilist, I think the local database for saving favorite animes is not needed anymore right ? @ITADORI-15 @JasonBlitz5 What do you think ?

What itadori said. There isn't a point to have it anymore. Also a random suggestion real quick,  can you try to add a genre search option?

**Comment by ITADORI-15** [comment]
Yeah that will be of great help to anime beginners.
Good one @JasonBlitz5

**Comment by GABIlopez** [comment]
Anime TV 
9anime 
Jkanimeapp 
anime FLV

**Comment by GABIlopez** [comment]
Anime play

**Comment by GABIlopez** [comment]
https://play.google.com/store/apps/details?id=net.DesiBit.Anime1X

**Comment by GABIlopez** [comment]
![Screenshot_20220131-191638_Google Play Store.jpg](https://user-images.githubusercontent.com/32043783/151882331-ce6e018c-0280-4c17-931b-0ad2a7a59d86.jpg)

**Comment by GABIlopez** [comment]
Anime Watch Sub & Dub Shows

**Comment by ITADORI-15** [comment]
@GABIlopez 
Why do u need this app when it has ads
Animity is better ryt...without ads

**Comment by ITADORI-15** [comment]
Bro u done?
So early??😲😲

**Comment by kl3jvi** [comment]
Not yet , I am still making some changes but its taking shape. I have added authentication, retrieving favorites, what animes you are planning to watch completed or watching currently. Added an option for guest login aswell. Now i will have to make favorite toggle work from within app and some small ui changes and It will be done for a beta release

**Comment by ITADORI-15** [comment]
Amazing bro 
U really took very less time than Expected
