### ISSUE TITLE
App Logo

### ISSUE THREAD

**Issue by kl3jvi** [kl3jvi/animity#45]
I think the logo the app is using right now is pretty simple and ugly to be honest. Can someone with good skills in graphic design, design a logo for animity. Use your imagination and I will make a poll so we can choose the best logo for the app!

**Comment by GABIlopez** [comment]
Anime play app

**Comment by ITADORI-15** [comment]
Bro there are templates in canva @kl3jvi They are pretty good.

**Comment by ITADORI-15** [comment]
I really dont know anything abt how to design a logo
So googling everything I found canva which had this abstract template check it...looks something like this
![Animity.png](https://user-images.githubusercontent.com/83289685/151917287-32e99a30-cc94-4400-9084-94f450b3528b.png)
It just represents A

**Comment by ProminentChrystal** [comment]
A plain "A" would look boring. If anyone can draw something simple by paper and pencil I could try to illustrate it. I'm not good at drawing things myself. As an idea, maybe a cat or something cute using the letter α? Or maybe something less related? Like a slime?

**Comment by LvClFER** [comment]
![Circle-02](https://user-images.githubusercontent.com/52974913/152203341-c90fbbd5-9464-44d5-821e-3a87ddb940bf.png)
![Semi-Circle-02](https://user-images.githubusercontent.com/52974913/152203345-0bce7de8-cdc3-4255-be77-87b35f760b65.png)
![Square-02](https://user-images.githubusercontent.com/52974913/152203348-e3d347c3-70d9-426e-8005-165b42f328da.png)

**Comment by LvClFER** [comment]
![Orangie](https://user-images.githubusercontent.com/52974913/152204554-5b39248d-f8c9-4f50-89a7-86738332e386.png)

**Comment by kl3jvi** [comment]
I like the second one. Can we chat in private so we can do a nice logo?

**Comment by kl3jvi** [comment]
@LvClFER can you recreate this logo as an svg? 
![e98106edbe1f531f512cfc59b4aa75e7](https://user-images.githubusercontent.com/40796367/152207903-ac11d5bd-6e41-4c76-895f-0d6c0b71fbb8.gif)

**Comment by LvClFER** [comment]
> I like the second one. Can we chat in private so we can do a nice logo?

sure

**Comment by LvClFER** [comment]
> @LvClFER can you recreate this logo as an svg? ![e98106edbe1f531f512cfc59b4aa75e7](https://user-images.githubusercontent.com/40796367/152207903-ac11d5bd-6e41-4c76-895f-0d6c0b71fbb8.gif)

i can try

**Comment by kl3jvi** [comment]
email me kl3jvi@protonmail.com

**Comment by GABIlopez** [comment]
https://github.com/saikou-app/saikou/releases/download/1.0.10/Saikou.1.0.10.4_fixed.apk
