### ISSUE TITLE
Are u done bro?


### ISSUE THREAD

**Issue by ITADORI-15** [kl3jvi/animity#48]
Bro can't wait longer😭
How long will it take.........
Thanx in advance....

**Comment by GABIlopez** [comment]
![Animeflv pro.png](https://user-images.githubusercontent.com/32043783/152451331-e57173c6-d01a-4340-a4a6-21ae64c66889.png)

**Comment by GABIlopez** [comment]
![unnamed.png](https://user-images.githubusercontent.com/32043783/152451380-739f76dc-4d5b-42e8-8a43-3bbbf5f27096.png)

**Comment by GABIlopez** [comment]
![Animeflv pro.png](https://user-images.githubusercontent.com/32043783/152451448-6a1b8e25-198c-4258-b007-e69aa63c517c.png)

**Comment by GABIlopez** [comment]
![unnamed (1).png](https://user-images.githubusercontent.com/32043783/152451492-f80ec6ff-ea48-4206-af97-a8b3c5e87ca7.png)

**Comment by GABIlopez** [comment]
![images.png](https://user-images.githubusercontent.com/32043783/152451511-0ff123e6-cfc3-48ae-b8ac-a66acd96de90.png)

**Comment by GABIlopez** [comment]
![images (1).png](https://user-images.githubusercontent.com/32043783/152452075-9dc27390-1bc0-4cd2-b12e-65a4d35b264d.png)

**Comment by GABIlopez** [comment]
![images.jpeg](https://user-images.githubusercontent.com/32043783/152452097-efb3f920-4f0f-48f0-b2d9-9067d8baf5f3.jpeg)

**Comment by GABIlopez** [comment]
![images (1).jpeg](https://user-images.githubusercontent.com/32043783/152452113-5fb7156e-9c05-48cd-9fb9-b27bba702672.jpeg)

**Comment by GABIlopez** [comment]
![icon.png](https://user-images.githubusercontent.com/32043783/152452127-3f69189a-a65c-416d-8766-dfb12162a9df.png)

**Comment by GABIlopez** [comment]
![icon (1).png](https://user-images.githubusercontent.com/32043783/152452148-d88c04c1-1a7c-4f08-a045-a4290237640d.png)

**Comment by GABIlopez** [comment]
![descarga.png](https://user-images.githubusercontent.com/32043783/152452168-e36fd280-dac7-4a9f-8e49-85831e8dd421.png)

**Comment by GABIlopez** [comment]
![stream-your-favorite-anime-all-of-days-at-9anime-newss-podcast.jpg.81f211879419ba4059a89bb2d61836d3.jpg](https://user-images.githubusercontent.com/32043783/152452181-0aa43906-6964-43b1-870d-e47b6ce63767.jpg)

**Comment by GABIlopez** [comment]
![09ec5b48494864f30e0de5f23ee8bcc864ca7188.jpg](https://user-images.githubusercontent.com/32043783/152452194-5a600923-dbd2-48ab-88ed-9a0bca0a873f.jpg)

**Comment by GABIlopez** [comment]
![images (2).png](https://user-images.githubusercontent.com/32043783/152452212-dd8db9b4-2051-4f65-b9e9-475288b195ee.png)

**Comment by GABIlopez** [comment]
![unnamed (2).png](https://user-images.githubusercontent.com/32043783/152452225-e7d9035b-e291-4960-bcd8-89ff0640efcd.png)

**Comment by GABIlopez** [comment]
![animelablogo.png](https://user-images.githubusercontent.com/32043783/152452246-da1b1b20-3397-410e-95b0-eda121550571.png)

**Comment by ITADORI-15** [comment]
@kl3jvi 
Bro u done?......I really cant wait 2 c ur app....with anilist...😋😋...
