### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JasonBlitz5** [kl3jvi/animity#49]
I mentioned this a while back but can you try to add an Tags/Genre search option so that way people can search for their favorite genres?

**Comment by ITADORI-15** [comment]
Since he is already integrating with anilist maybe that option would already be there...

**Comment by GABIlopez** [comment]
Anime X Stream

**Comment by GABIlopez** [comment]
https://github.com/mukul500/AnimeXStream/releases/download/v0.4.0/AnimexStream-v0.4.0-arm64-v8a-release.apk

**Comment by GABIlopez** [comment]
https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0
