### ISSUE TITLE
Navigation bar on android 

### ISSUE THREAD

**Issue by Dmnboruto** [kl3jvi/animity#50]
I have an issue where playing a video on this app it shows the navigation bar at the bottom with is annoying but the full-strength button doesn't fix this is the only app that has the problem

**Comment by ITADORI-15** [comment]
Exit the player and open again.....but this time dont try to change the resolution....that is what brings the issue...or even switching b/w apps

**Comment by GABIlopez** [comment]
https://github.com/mukul500/AnimeXStream/releases/download/v0.4.0/AnimexStream-v0.4.0-arm64-v8a-release.apk

**Comment by GABIlopez** [comment]
https://github.com/SuperMarcus/NineAnimator

**Comment by GABIlopez** [comment]
https://github.com/SuperMarcus/NineAnimator/releases/download/1.2.7-6/NineAnimator_1.2.7_Build_6.ipa
