### ISSUE TITLE
Can't increase playback speed to 4x like other anime streaming website

### ISSUE THREAD

**Issue by JustaUser0** [kl3jvi/animity#67]
Can't increase playback speed to 4x like other anime streaming website.Can't select Default playback speed. Please remove the trackers

**Comment by kl3jvi** [comment]
What do you mean?

**Comment by JustaUser0** [comment]
> What do you mean?

Add Default playback speed and option to increase playback speed to 3x. Please Remove the trackers

![animity](https://user-images.githubusercontent.com/102304141/160586556-8b3c5973-9c60-46ef-9771-2aad61bb8e05.jpg)

**Comment by kl3jvi** [comment]
@JustaUser0 sorry for asking but why do you need a 4x speed? I think this will not be possible to be added in any further build.
As for the trackers, I am using firebase analytics to track and solve the bugs. I have added this with permission of the users. I will try to add a toggle to choose if you want to help improving the app or not.
