### ISSUE TITLE
Video Player issue 

### ISSUE THREAD

**Issue by JasonBlitz5** [kl3jvi/animity#73]
Some anime will play and others won't play (I tired to send a video and it wouldn't let me. Also the anime that worked is AoT)

![VideoCapture_20220328-135405](https://user-images.githubusercontent.com/97261684/160458141-304853c0-8ed0-430c-86cc-229565232800.jpg)
![VideoCapture_20220328-135419](https://user-images.githubusercontent.com/97261684/160458173-c95bc28d-f8bc-4dad-ab9e-ac5423f9bdef.jpg)
![VideoCapture_20220328-135425](https://user-images.githubusercontent.com/97261684/160458176-9a0e2656-5ffa-4e33-ad5a-2bfce7a43caa.jpg)

**Comment by kl3jvi** [comment]
This is a bug with gogoanime servers, I will try to migrate the app with another provider.
