### ISSUE TITLE
3 bugs.....so far

### ISSUE THREAD

**Issue by ITADORI-15** [kl3jvi/animity#76]
First up the animes wont play....idk y
![Screenshot_20220329-175803_Animity.jpg](https://user-images.githubusercontent.com/83289685/160611499-bd1a78eb-e0e2-4cae-b03b-85a458145ef6.jpg)
And if I click on any anime from the profile section no episodes are shown
![Screenshot_20220329-175856_Animity.jpg](https://user-images.githubusercontent.com/83289685/160611649-5a663e18-6695-4e1c-b443-a3e4a83604c3.jpg)
And also in settings...there is another settings button...idk how 2 put it but hve a look....
![Screenshot_20220329-175732_Animity.jpg](https://user-images.githubusercontent.com/83289685/160611772-b1c1af12-fa59-4f9f-807f-fc926ff5657e.jpg)
These r the ones I saw so far.......
The major one being animes not playing....😁
@kl3jvi

**Comment by JasonBlitz5** [comment]
I'm having the same issues

**Comment by kl3jvi** [comment]
Fixed #83
